include:
  - project: nse/ci
    file:
      - /ci/lib/tox-docker.yml
  - project: neuromath/ci
    file:
      - /ci/lib/pytest-template.yml

.tox-template:
  variables:
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

.pytest-template:
  variables:
    COVERAGE_FILE: .coverage-${CI_JOB_NAME}
    SYS_PACKAGES: git
  artifacts:
    reports:
      junit: My-Project/reports/pytest-${CI_JOB_NAME}.xml
    paths:
      - My-Project/.coverage-${CI_JOB_NAME}

py37-gitlab-withPy37-withToml:
  extends: .pytest-template

py38-gitlab-withoutPy37-withToml:
  extends: .pytest-template

py37-github-withPy37-withToml:
  extends: .pytest-template

py38-github-withoutPy37-withToml:
  extends: .pytest-template

py37-gitlab-withPy37-withoutToml:
  extends: .pytest-template

py38-gitlab-withoutPy37-withoutToml:
  extends: .pytest-template

py37-github-withPy37-withoutToml:
  extends: .pytest-template

py38-github-withoutPy37-withoutToml:
  extends: .pytest-template

# Create a tag with SemVer format
.do-tag: &do-tag
  - |
    # If tag already exists
    if [[ $(git tag -l "$TAG_NAME") ]]; then
      if [[ "$PACKAGE_RELEASE" == dev ]]; then
        echo "Clearing existing dev tag $TAG_NAME"
        curl -s -X DELETE -H "Authorization: Bearer $OAUTH2_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/tags/$TAG_NAME"
      else
        echo "Skip tag and release creation because $TAG_NAME already exists"
        exit 0
      fi
    fi
  - echo "Adding tag $TAG_NAME"
  - git tag -f -a "$TAG_NAME" -m "$TAG_NAME"
  - git push origin $TAG_NAME

.do-release: &do-release
  - |
    # Exit if not a release
    if [[ "$PACKAGE_RELEASE" != release ]]; then
      echo "Skip release creation for $PACKAGE_RELEASE version: $PACKAGE_VERSION"
      exit 0
    fi
  - |
    PAYLOAD=$(cat <<EOF
    {
      "name": "Version $PACKAGE_VERSION",
      "tag_name": "$TAG_NAME"
    }
    EOF
    )
  - 'curl --fail --request POST
    --header "Content-Type: application/json"
    --header "Authorization: Bearer ${CI_JOB_TOKEN}"
    --data "$PAYLOAD"
    "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases" && echo'

.do-notify: &do-notify
  - |
    # Exit if SLACK_WEBHOOK is not set
    if [[ -z $SLACK_WEBHOOK ]]; then
      echo 'Notification not sent because $SLACK_WEBHOOK is not set'
      exit 0
    fi
  - |
    PAYLOAD=$(cat <<EOF
    {
      "username": "Release Notifier",
      "icon_emoji": ":loudspeaker:",
      "type": "mrkdwn",
      "text": "A new <${RELEASE_URL}|release> is available! <${PACKAGE_URL}|*${PACKAGE_NAME} ${PACKAGE_VERSION}*>"
    }
    EOF
    )
  - 'curl --fail --request POST
    --header "Content-Type: application/json"
    --data "$PAYLOAD"
    "$SLACK_WEBHOOK" || true'

tag:
  stage: release
  before_script:
    - if [[ -z $OAUTH2_TOKEN ]]; then echo 'Please set the $OAUTH2_TOKEN variable'; exit 1; fi
    - !reference [.define-functions]
    - !reference [.docker, load-python-39]
    - !reference [.setup-venv]
    - git config --global user.email "bbprelman@epfl.ch"
    - git config --global user.name "BBP Release Manager"
    - git remote remove origin
    - git remote add origin "${CI_REPOSITORY_URL/#https:\/\/*@/https://oauth2:${OAUTH2_TOKEN}@}"
  script:
    - !reference [.load-package-props]
    - TAG_NAME="${PACKAGE_VERSION}"
    - RELEASE_URL="${CI_PROJECT_URL}/-/releases/${TAG_NAME}"
    - *do-tag
    - *do-release
    - *do-notify
  dependencies: []
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
