include:
  - project: nse/ci
    file:
      - /ci/lib/tox-docker.yml
      - /ci/jobs/check-version.yml
      - /ci/jobs/check-packaging.yml
      - /ci/jobs/lint.yml
      - /ci/jobs/docs.yml
      - /ci/jobs/tag.yml
  - project: neuromath/ci
    file:
      - /ci/lib/pytest-template.yml
      - /ci/jobs/py37.yml
      - /ci/jobs/py38.yml
      - /ci/jobs/py39.yml
      - /ci/jobs/coverage.yml

.tox-template:
  variables:
    PIP_PACKAGES: tox copier copier-templates-extensions jinja2-time
    PRE_BUILD_COMMAND: "git config --global user.name '$GITLAB_USER_NAME'; git config --global user.email '$GITLAB_USER_EMAIL'; copier --vcs-ref=HEAD --overwrite --defaults . My-Project; cd My-Project; git init; git add --all; git commit -m 'Initial commit';"
    KUBERNETES_MEMORY_LIMIT: 6Gi
    KUBERNETES_MEMORY_REQUEST: 6Gi

.pytest-template:
  variables:
    COVERAGE_FILE: .coverage-${CI_JOB_NAME}
  artifacts:
    reports:
      junit: My-Project/reports/pytest-${CI_JOB_NAME}.xml
    paths:
      - My-Project/.coverage-${CI_JOB_NAME}

check-version:
  variables:
    PRE_BUILD_COMMAND: !reference [.tox-template, variables, PRE_BUILD_COMMAND]

check-packaging:
  variables:
    PRE_BUILD_COMMAND: !reference [.tox-template, variables, PRE_BUILD_COMMAND]

docs:
  variables:
    PRE_BUILD_COMMAND: !reference [.tox-template, variables, PRE_BUILD_COMMAND]

lint:
  variables:
    PRE_BUILD_COMMAND: !reference [.tox-template, variables, PRE_BUILD_COMMAND]

coverage:
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: My-Project/coverage.xml
