[tox]
minversion = 4.20
envlist = py312
skip_missing_interpreters = true

[testenv]
deps =
    copier>=8
    copier-templates-extensions
    jinja2-time
    pytest>=8
    pyyaml>=6
    tox>=4.20
commands =
    pytest {posargs}
