[tox]
skipsdist = true
minversion = 3.1
ignore_basepython_conflict = true

[testenv]
basepython = python3.9

[testenv:update-docs]
deps =
    click
    sphinx
commands =
    python {toxinidir}/utils/update_sphinx.py --output-path {toxinidir}/\{\{cookiecutter.package_name\}\}/doc/
