[tox]
skipsdist = true
minversion = 3.1
ignore_basepython_conflict = true

envlist =
    py{37,38}-{gitlab,github}-{withToml,withoutToml}

[testenv]
setenv =
    gitlab: PIP_EXTRA_INDEX_URL = https://bbpteam.epfl.ch/repository/devpi/simple
    gitlab: REPOSITORY_PROVIDER = gitlab
    github: REPOSITORY_PROVIDER = github
    withToml: USE_TOML = yes
    withoutToml: USE_TOML = no
pass_env =
    CI
    GITHUB_ACTIONS
    GITLAB_CI
deps =
    copier>=8
    copier-templates-extensions
    jinja2-time
    pydantic<2
    tox
allowlist_externals =
    /bin/bash
    git
commands =
    copier copy --UNSAFE --overwrite --defaults -d "repository_provider={env:REPOSITORY_PROVIDER}" -d "use_pyproject_toml={env:USE_TOML}" -r HEAD {toxinidir} {envtmpdir}/My-Project
    /bin/bash -c 'cd {envtmpdir}/My-Project; pwd; git init; git add --all; git config user.name "John Doe"; git config user.email "john.doe@epfl.ch"; git commit -m "Initial commit"; {envpython} -m tox'

[testenv:update-docs]
deps =
    click
    sphinx
commands =
    {envpython} {toxinidir}/utils/update_sphinx.py --output-path {toxinidir}/template/docs/
